# The base URL of the site; the only required configuration variable.
base_url = "https://github.com/Absence0760/project-personal-website"

# The site title and description; used in feeds by default.
title       = "Jared Howard"
description = "Writing about things I find interesting."

# Configuration of the Markdown rendering
[markdown]
